
pipeline{
    agent {
      node {
        label 'jenkins-slave'
      }
    }

    tools {
         maven 'MAVEN_HOME'
         jdk 'JAVA_HOME'
    }

    stages{
       stage('Git Checkout'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github access', url: 'https://github.com/GoudSagar/Hello-World-Code.git']]])
            }
        }
	stage('Deploying web application container to Kubernetes') {
           steps {
	       sh '''
                  kubectl create -f  Docker/deployment.yaml
                  sleep 10
		  kubectl create -f Docker/service.yaml
                '''
                 }
             }
          
     }
}
